dist: trusty
sudo: false
language: python
python:
  - 2.7
  - 3.6
  - pypy-5.4.1
  - pypy3.3-5.2-alpha1
  - 2.6
  - 3.3
  - 3.4
  - 3.5
  - nightly
install:
  - ./travis_install.sh
script:
  - tox
after_success:
  - coveralls
  - python setup.py bdist_wheel sdist
